name: Snapshot Release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checking out
      - uses: actions/checkout@v1

      # Using caches
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Setup JDK
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # The following generates a debug APK
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build githubRelease
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: intellij-smart-align-plugin
          path: build/distributions
